
document.addEventListener('DOMContentLoaded', () => {
    let contenido = document.createElement("h1");
    contenido.textContent = `
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    sin tele y sin cerveza Homer pierde la cabeza, <br>
    `
    document.body.prepend(contenido);
 });
