
document.addEventListener('DOMContentLoaded', () => {
    let contenido = document.createElement("h1");
    contenido.textContent = `sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,sin tele y sin cerveza homer pierde la cabeza,
    `
    document.body.prepend(contenido);
 });
