const books = [
    {
      isbn: '978-0132350884',
      title: 'Clean Code',
      subtitle: 'A Handbook of Agile Software Craftsmanship',
      author: 'Robert C. Martin',
      published: '2008-08-01',
      publisher: 'Prentice Hall',
      pages: 464,
      description: 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees.',
      website: 'https://www.goodreads.com/book/show/3735293-clean-code'
    },
    {
      isbn: '978-0201633610',
      title: 'Design Patterns',
      subtitle: 'Elements of Reusable Object-Oriented Software',
      author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
      published: '1994-10-21',
      publisher: 'Addison-Wesley Professional',
      pages: 395,
      description: 'Capturing a wealth of experience about the design of object-oriented software.',
      website: 'https://www.goodreads.com/book/show/85009.Design_Patterns'
    },
    {
      isbn: '978-0262033848',
      title: 'Introduction to Algorithms',
      subtitle: '',
      author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
      published: '2009-07-31',
      publisher: 'The MIT Press',
      pages: 1312,
      description: 'The standard textbook on algorithms, covering a broad range of algorithms in depth.',
      website: 'https://www.goodreads.com/book/show/108986.Introduction_to_Algorithms'
    },
    {
      isbn: '978-0131103627',
      title: 'The C Programming Language',
      subtitle: '',
      author: 'Brian W. Kernighan, Dennis M. Ritchie',
      published: '1988-04-01',
      publisher: 'Prentice Hall',
      pages: 272,
      description: 'Known as K&R, this book is considered the bible of C programming.',
      website: 'https://www.goodreads.com/book/show/515601.The_C_Programming_Language'
    },
    {
      isbn: '978-0596007126',
      title: 'Head First Design Patterns',
      subtitle: '',
      author: 'Eric Freeman, Bert Bates, Kathy Sierra, Elisabeth Robson',
      published: '2004-10-25',
      publisher: 'O\'Reilly Media',
      pages: 694,
      description: 'A brain-friendly guide to software patterns.',
      website: 'https://www.goodreads.com/book/show/58128.Head_First_Design_Patterns'
    },
    {
      isbn: '978-0137081073',
      title: 'Effective Java',
      subtitle: '',
      author: 'Joshua Bloch',
      published: '2008-05-28',
      publisher: 'Addison-Wesley Professional',
      pages: 346,
      description: 'Are you looking for a deeper understanding of the Java programming language so that you can write code that is clearer, more correct, more robust, and more reusable?',
      website: 'https://www.goodreads.com/book/show/34927404-effective-java'
    },
    {
      isbn: '978-1617292231',
      title: 'JavaScript Patterns',
      subtitle: 'Build Better Applications with Coding and Design Patterns',
      author: 'Stoyan Stefanov',
      published: '2010-09-09',
      publisher: 'O\'Reilly Media',
      pages: 240,
      description: 'What\'s the best approach for developing an application with JavaScript?',
      website: 'https://www.goodreads.com/book/show/9428723-javascript-patterns'
    },
    {
      isbn: '978-1491950296',
      title: 'You Don\'t Know JS: ES6 & Beyond',
      subtitle: '',
      author: 'Kyle Simpson',
      published: '2015-12-27',
      publisher: 'O\'Reilly Media',
      pages: 278,
      description: 'No matter how much experience you have with JavaScript, odds are you don’t fully understand the language.',
      website: 'https://www.goodreads.com/book/show/23346649-you-don-t-know-js'
    },
    {
      isbn: '978-0133594140',
      title: 'JavaScript: The Good Parts',
      subtitle: '',
      author: 'Douglas Crockford',
      published: '2008-05-01',
      publisher: 'O\'Reilly Media',
      pages: 176,
      description: 'Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined.',
      website: 'https://www.goodreads.com/book/show/2998152-javascript'
    },
    {
      isbn: '978-0201616224',
      title: 'The Pragmatic Programmer',
      subtitle: 'Your Journey to Mastery',
      author: 'Andrew Hunt, David Thomas',
      published: '1999-10-20',
      publisher: 'Addison-Wesley Professional',
      pages: 352,
      description: 'Straight from the programming trenches, The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process.',
      website: 'https://www.goodreads.com/book/show/4099.The_Pragmatic_Programmer'
    },
    {
      isbn: '978-0061120084',
      title: 'To Kill a Mockingbird',
      subtitle: '',
      author: 'Harper Lee',
      published: '1960-07-11',
      publisher: 'J.B. Lippincott & Co.',
      pages: 281,
      description: 'A novel about the serious issues of rape and racial inequality.',
      website: 'https://www.goodreads.com/book/show/2657.To_Kill_a_Mockingbird'
    },
    {
      isbn: '978-0451524935',
      title: '1984',
      subtitle: '',
      author: 'George Orwell',
      published: '1949-06-08',
      publisher: 'Secker & Warburg',
      pages: 328,
      description: 'A dystopian novel set in a totalitarian society ruled by Big Brother.',
      website: 'https://www.goodreads.com/book/show/5470.1984'
    },
    {
      isbn: '978-0743273565',
      title: 'The Great Gatsby',
      subtitle: '',
      author: 'F. Scott Fitzgerald',
      published: '1925-04-10',
      publisher: 'Charles Scribner\'s Sons',
      pages: 180,
      description: 'A critique of the American Dream set in the Roaring Twenties.',
      website: 'https://www.goodreads.com/book/show/4671.The_Great_Gatsby'
    },
    {
      isbn: '978-0140283297',
      title: 'Pride and Prejudice',
      subtitle: '',
      author: 'Jane Austen',
      published: '1813-01-28',
      publisher: 'T. Egerton',
      pages: 279,
      description: 'A classic novel about manners, upbringing, and marriage in early 19th century England.',
      website: 'https://www.goodreads.com/book/show/1885.Pride_and_Prejudice'
    },
    {
      isbn: '978-0307277671',
      title: 'The Catcher in the Rye',
      subtitle: '',
      author: 'J.D. Salinger',
      published: '1951-07-16',
      publisher: 'Little, Brown and Company',
      pages: 214,
      description: 'A story about adolescent alienation and loss of innocence in the protagonist Holden Caulfield.',
      website: 'https://www.goodreads.com/book/show/5107.The_Catcher_in_the_Rye'
    },
    {
      isbn: '978-0140449136',
      title: 'Crime and Punishment',
      subtitle: '',
      author: 'Fyodor Dostoevsky',
      published: '1866-01-01',
      publisher: 'The Russian Messenger',
      pages: 671,
      description: 'A psychological drama of a young intellectual who commits a murder.',
      website: 'https://www.goodreads.com/book/show/7144.Crime_and_Punishment'
    },
    {
      isbn: '978-0553382563',
      title: 'The Hobbit',
      subtitle: '',
      author: 'J.R.R. Tolkien',
      published: '1937-09-21',
      publisher: 'George Allen & Unwin',
      pages: 310,
      description: 'A fantasy novel introducing the world of Middle-earth and the quest of Bilbo Baggins.',
      website: 'https://www.goodreads.com/book/show/5907.The_Hobbit_or_There_and_Back_Again'
    },
    {
      isbn: '978-0060850524',
      title: 'Brave New World',
      subtitle: '',
      author: 'Aldous Huxley',
      published: '1932-01-01',
      publisher: 'Chatto & Windus',
      pages: 268,
      description: 'A dystopian novel exploring themes of technology, control, and individuality.',
      website: 'https://www.goodreads.com/book/show/5129.Brave_New_World'
    },
    {
      isbn: '978-0142437230',
      title: 'Moby-Dick',
      subtitle: '',
      author: 'Herman Melville',
      published: '1851-10-18',
      publisher: 'Harper & Brothers',
      pages: 635,
      description: 'An epic tale of obsession and the pursuit of the elusive white whale, Moby Dick.',
      website: 'https://www.goodreads.com/book/show/153747.Moby_Dick_or_the_Whale'
    },
    {
      isbn: '978-0143039433',
      title: 'The Odyssey',
      subtitle: '',
      author: 'Homer',
      published: '-800-01-01',
      publisher: 'Ancient Greece',
      pages: 541,
      description: 'An epic poem following the adventures of Odysseus on his journey home from the Trojan War.',
      website: 'https://www.goodreads.com/book/show/1381.The_Odyssey'
    },
    {
      isbn: '978-0679720201',
      title: 'One Hundred Years of Solitude',
      subtitle: '',
      author: 'Gabriel García Márquez',
      published: '1967-05-30',
      publisher: 'Harper & Row',
      pages: 417,
      description: 'A magical realism novel chronicling the Buendía family over seven generations.',
      website: 'https://www.goodreads.com/book/show/320.One_Hundred_Years_of_Solitude'
    },
    {
      isbn: '978-0307949486',
      title: 'The Road',
      subtitle: '',
      author: 'Cormac McCarthy',
      published: '2006-09-26',
      publisher: 'Alfred A. Knopf',
      pages: 287,
      description: 'A post-apocalyptic tale of a father and son journeying through a desolate landscape.',
      website: 'https://www.goodreads.com/book/show/6288.The_Road'
    },
    {
      isbn: '978-0316769488',
      title: 'The Alchemist',
      subtitle: '',
      author: 'Paulo Coelho',
      published: '1988-01-01',
      publisher: 'HarperTorch',
      pages: 208,
      description: 'A philosophical story about following your dreams and reading the omens strewn along life\'s path.',
      website: 'https://www.goodreads.com/book/show/865.The_Alchemist'
    },
    {
      isbn: '978-0743482745',
      title: 'Hamlet',
      subtitle: '',
      author: 'William Shakespeare',
      published: '1603-01-01',
      publisher: 'Simon & Schuster',
      pages: 342,
      description: 'A tragedy about Prince Hamlet\'s quest for revenge against his uncle Claudius.',
      website: 'https://www.goodreads.com/book/show/1420.Hamlet'
    },
    {
      isbn: '978-0553296983',
      title: 'Dune',
      subtitle: '',
      author: 'Frank Herbert',
      published: '1965-08-01',
      publisher: 'Chilton Books',
      pages: 412,
      description: 'A science fiction epic about politics, religion, and ecology on the desert planet Arrakis.',
      website: 'https://www.goodreads.com/book/show/234225.Dune'
    }
  ];